### ISSUE TITLE
Package folder is empty

### ISSUE THREAD

**Issue by Midnight0507** [Godiesc/floorp-gx#1]
Package folder isnt available 
![image](https://github.com/Godiesc/floorp-gx/assets/110766220/f271e379-f0ac-4ff6-a4e1-ccbf77b6d7b8)

**Comment by Godiesc** [comment]
hi, sorry for the inconvenient, you can download now from `code -> download zip`, in the future I will add a release version when the theme becomes solid.

**Comment by Midnight0507** [comment]
okay got it :))
