### ISSUE TITLE
Disable bookmark toolbar autohide

### ISSUE THREAD

**Issue by raziel6868** [Godiesc/floorp-gx#3]
I recently discovered that you made OperaGX userChrome.css for Floorp and I love it. I have a question though: How can I make the bookmark bar always visible instead of automatically hiding itself ?

**Comment by Godiesc** [comment]
hi, I made the basic theme compatible, but I didn't update it in a while, I hope to work on it in a near future. When you show your bookmark-bar without the auto-hide it, that action cause some problems, for that reason I did the auto-hide, if you want you can delete the [section of that](https://github.com/Godiesc/floorp-gx/blob/main/chrome/components/ogx_left-sidebar.css#L286-L363) in `ogx_left-sidebar.css` and you will see the problems.
