### ISSUE TITLE
Not really a issue but like there is space down the settings how do i edit it so tht the space is gone in left sidebar bottonside

### ISSUE THREAD

**Issue by Midnight0507** [Godiesc/floorp-gx#4]
![image](https://github.com/Godiesc/floorp-gx/assets/110766220/4dc96bf6-551f-43a4-89ae-470f4548fa64)

**Comment by Godiesc** [comment]
hi,
you can change that in `ogx_left-sidebar.css` file, in the line 11 try a smaller number, maybe 66px.

![imagen](https://github.com/Godiesc/floorp-gx/assets/22057609/348cb3f3-83a7-4f43-8ed9-1237451d2b00)
