### ISSUE TITLE
Sidebar settings button and private window wordmark being cut off

### ISSUE THREAD

**Issue by Reconnect3** [Godiesc/floorp-gx#7]
![floorp_W8e1uQeTkx cleaned](https://github.com/user-attachments/assets/b752a4e2-6f43-48d9-ab70-53c50fa06f03)

**Comment by Reconnect3** [comment]
I fixed both myself but I don't know how to make a pull request or anything

**Comment by Godiesc** [comment]
hi,
i solved the private window issue, but I don't have the 'Sidebar settings button' cut off, only if I have a lot of items in that sidebar I see that bottom buttons cut off below, and you can access by scrolling the mouse wheel.
I see you didn't apply a compatible theme, you can choose one of my themes from here: [Compatible themes](https://github.com/Godiesc/floorp-gx?tab=readme-ov-file#temas---themes) or use my extension: [GX theme styles](https://addons.mozilla.org/es/firefox/addon/gx-theme-styles/)

**Comment by Godiesc** [comment]
I tested again and that issue happens when you active the bookmarks-bar, I will work on it.
Update: Solved with the latest update, thanks for report the issue. 💙
