### ISSUE TITLE
Split tab icon  is misplaced 

### ISSUE THREAD

**Issue by Midnight0507** [Godiesc/floorp-gx#8]
![image](https://github.com/user-attachments/assets/873e45e8-2009-47db-94ac-fd3a54ef2de1)

**Comment by Godiesc** [comment]
hi,
how do I active that icon, I open my tabs and that icon didn't appear. Is it some feature I explicit should active?

**Comment by Godiesc** [comment]
the `ogx_urlbar-searchbar.css` file was updated to solve that issue.

**Comment by Midnight0507** [comment]
sry for late response and thanks for fixing
